<?php

use Illuminate\Database\Seeder;

class CategoryTableSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('categories')->insert([
			[
				'name' => 'Agama',
				'code' => 'HR; HRA; HRAM; HRAX; HRC; HRCL; HRCL1; HRCS; HRCV; HRCV1; HRCR1; HRCX6',
				'parent_id' => 0,
			],
			[
				'name' => 'Bahasa',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Biografi',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Bisnis & Manajemen',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Buku Anak & Remaja',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Buku Sekolah',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Busana',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Computer & Teknologi',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Ekonomi & Akuntansi',
				'code' => 'KF; KFFM; KFFX',
				'parent_id' => 0,
			],
			[
				'name' => 'Hukum & Politik',
				'code' => 'LA; JP',
				'parent_id' => 0,
			],
			[
				'name' => 'Kesehatan',
				'code' => 'VFVG; VFV; VFVK',
				'parent_id' => 0,
			],
			[
				'name' => 'Keterampilan',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Masakan',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Musik',
				'code' => 'AVH',
				'parent_id' => 0,
			],
			[
				'name' => 'Novel',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Olahraga',
				'code' => 'WSJA1',
				'parent_id' => 0,
			],
			[
				'name' => 'Pengembangan Diri',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Pertanian, Peternakan & Perikanan',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Psikologi',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Seni & Desain',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Sosial & Budaya',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Teknik',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Travel',
				'code' => 'WTL; WTD; WTHA',
				'parent_id' => 0,
			],
			[
				'name' => 'Lihat semua eBook LIVI',
				'code' => null,
				'parent_id' => 0,
			],
			[
				'name' => 'Biograpy : General',
				'code' => 'BG; BGA; BGS; BGH; BGX; BGBA; BGXA',
				'parent_id' => 3,
			],
			[
				'name' => 'DIARIES, LETTERS & JOURNALS',
				'code' => 'BJ',
				'parent_id' => 3,
			],
			[
				'name' => 'Memoirs',
				'code' => 'BM',
				'parent_id' => 3,
			],
			[
				'name' => 'True Stories',
				'code' => 'BT; BTP',
				'parent_id' => 3,
			],
			[
				'name' => 'FINANCE & ACCOUNTING',
				'code' => 'KF; KFFM; KFFX',
				'parent_id' => 4,
			],
			[
				'name' => 'BUSINESS & MANAGEMENT',
				'code' => 'KJB; KJC; KJD; KJM; KJH; KJMV2; KJMV1; KJMV7; KJR; KJS; KJSU; KJMV5',
				'parent_id' => 4,
			],
			[
				'name' => 'Novel',
				'code' => 'YFM; YFY; YNR; YFU; YFW; YFD; YFB; YFC; YFT; YNM; YXF; YFA; YFR',
				'parent_id' => 5,
			],
			[
				'name' => 'Pendidikan',
				'code' => 'YQTU; YQR; YQC',
				'parent_id' => 5,
			],
			[
				'name' => 'Lihat semua buku anak & remaja',
				'code' => 'Y',
				'parent_id' => 5,
			],
			[
				'name' => 'SMP',
				'code' => 'PB; JF; AB; LNDA; PDD; CJB',
				'parent_id' => 6,
			],
			[
				'name' => 'SMA',
				'code' => 'CJB',
				'parent_id' => 6,
			],
			[
				'name' => 'SMK',
				'code' => 'TGB; TDPF; TVB; JNT; TQSW1; ANC; PSVH; PSVW1; UYU; KNX; WGM; UGN; TJF',
				'parent_id' => 6,
			],
			[
				'name' => 'Lihat semua buku sekolah',
				'code' => null,
				'parent_id' => 6,
			],
			[
				'name' => 'Digital',
				'code' => 'AJG; UDP',
				'parent_id' => 8,
			],
			[
				'name' => 'Hardware',
				'code' => 'UKPM',
				'parent_id' => 8,
			],
			[
				'name' => 'Software',
				'code' => 'UFBC; UFCE; ULDF; ULL',
				'parent_id' => 8,
			],
			[
				'name' => 'Programming',
				'code' => null,
				'parent_id' => 8,
			],
			[
				'name' => 'Lihat semua buku computer & teknologi',
				'code' => 'U',
				'parent_id' => 8,
			],
			[
				'name' => 'Lihat semua buku Ekonomi & Akuntansi',
				'code' => 'K',
				'parent_id' => 9,
			],
			[
				'name' => 'Lihat semua buku Hukum & Politik',
				'code' => 'L; JP',
				'parent_id' => 10,
			],
			[
				'name' => 'Fantasi',
				'code' => 'FM',
				'parent_id' => 15,
			],
			[
				'name' => 'Klasik',
				'code' => 'FC',
				'parent_id' => 15,
			],
			[
				'name' => 'Metropop/Chick lit/ Teen lit',
				'code' => null,
				'parent_id' => 15,
			],
			[
				'name' => 'Misteri',
				'code' => 'FF; FFC; FFH',
				'parent_id' => 15,
			],
			[
				'name' => 'Romantis',
				'code' => 'FR; FRD',
				'parent_id' => 15,
			],
			[
				'name' => 'Sastra',
				'code' => null,
				'parent_id' => 15,
			],
			[
				'name' => 'Sejarah',
				'code' => null,
				'parent_id' => 15,
			],
			[
				'name' => 'Lihat semua novel',
				'code' => null,
				'parent_id' => 15,
			],
			[
				'name' => 'Arsitektur',
				'code' => null,
				'parent_id' => 20,
			],
			[
				'name' => 'Desain Grafis',
				'code' => 'AKC',
				'parent_id' => 20,
			],
			[
				'name' => 'Fotografi',
				'code' => 'UDP',
				'parent_id' => 20,
			],
			[
				'name' => 'Lihat semua seni & desain',
				'code' => 'AK',
				'parent_id' => 20,
			],
			[
				'name' => 'Lihat semua buku Travel',
				'code' => 'WT',
				'parent_id' => 23,
			]
		]);
		DB::table('categories')->insert([
			// 58
			[
				'name' => 'Art, Music & Photography',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Biography & Memoirs',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Business & Money',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Children\'s eBooks',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Comics & Graphic Novels',
				'code' => 'WH; FX; FZ',
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Computers & Technology',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Cookbooks, Food & Wine',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Crafts, Hobbies & Home',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Education & Teaching',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Engineering & Transportation',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Foreign Languanges',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Health, fitness & dieting',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'History',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Humor & Entertaiment',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Law',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Literature & Fiction',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Medical eBooks',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Mystery, Thriller & Suspense',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Non-fiction',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Parenting & Relationships',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Politics & Social Sciences',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Reference',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Religion & Spirituality',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Romance',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Science & Math',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Science Fiction & Fanstasy',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Self-help',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Sports & Outdoors',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Teen & Young Adult',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Travel',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'See all LIVI eBooks',
				'code' => null,
				'parent_id' => 0,
				'type' => 'international',
			],
			[
				'name' => 'Art',
				'code' => 'AC; AF; AG; AJ; AK; AM',
				'parent_id' => 58,
				'type' => 'international',
			],
			[
				'name' => 'Performing Arts',
				'code' => 'AN; AP; AS; AV',
				'parent_id' => 58,
				'type' => 'international',
			],
			[
				'name' => 'See all art, music & photography',
				'code' => 'A',
				'parent_id' => 58,
				'type' => 'international',
			],
			[
				'name' => 'Cultural Heritage',
				'code' => 'GM',
				'parent_id' => 59,
				'type' => 'international',
			],
			[
				'name' => 'Historical',
				'code' => 'BG; BJ; BK; BT',
				'parent_id' => 59,
				'type' => 'international',
			],
			[
				'name' => 'Literacy',
				'code' => 'BM',
				'parent_id' => 59,
				'type' => 'international',
			],
			[
				'name' => 'See all biography & memoirs',
				'code' => 'B',
				'parent_id' => 59,
				'type' => 'international',
			],
			[
				'name' => 'Accounting',
				'code' => 'KF',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Biography & History',
				'code' => 'BG; BJ; BK ',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Business Life',
				'code' => 'KJ; KN',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Economics',
				'code' => 'KC; KF; KJ ',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Education & Reference',
				'code' => 'GB; HB; JN; MR; YR; 4',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Entrepreneurship & Small business',
				'code' => 'KJ; KN',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Finance',
				'code' => 'KF; KJ',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Green Business',
				'code' => 'KJ',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Industries',
				'code' => 'KN',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'International',
				'code' => 'KC; KN',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Investing',
				'code' => 'KF; KJ',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Job Hunting & Careers',
				'code' => 'VS; KJ',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Marketing & Sales',
				'code' => 'KJ',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Organizational Behaviour',
				'code' => 'KC; KJ',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Personal Finance',
				'code' => 'KF; KJ; VS',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Real Estate',
				'code' => 'KF; KJ; LN',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Skills',
				'code' => 'MQ; TG; TH; TN; TR; TT; WS; YQ; 4E; 4K',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Taxation',
				'code' => 'KF; LN',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Technology',
				'code' => 'AJ; BG; JF; JN; KN; MM; PD; PN; RN; T; U; 4K',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'See all Business & Money',
				'code' => 'K',
				'parent_id' => 60,
				'type' => 'international',
			],
			[
				'name' => 'Action & Adventure',
				'code' => 'YB',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Activities & Games',
				'code' => 'YB',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Animals',
				'code' => 'YF; YN',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Art, Music & Photography',
				'code' => 'YQ',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Biographies',
				'code' => 'YN',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Cars, Trains & Things That Go',
				'code' => 'YB',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Comics & Graphic Novels',
				'code' => 'FX',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Computer & Technology',
				'code' => 'YQ',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Easy Learning',
				'code' => 'YB',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Education & Reference',
				'code' => 'YF; YR',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Fairy Tales, Folk Tales & Myths',
				'code' => 'YF',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Geography & Cultures',
				'code' => 'YQ',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Growing Up & Facts of Life',
				'code' => 'YX',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'History',
				'code' => 'YN',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Humor',
				'code' => 'YN',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Literature & Fiction',
				'code' => 'YF; YQ',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Mysteries & Detectives',
				'code' => 'YN',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Religions',
				'code' => 'YQ',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Science Fiction, Fantasy & Scary Stories',
				'code' => 'YF',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Science, Nature & How it Works',
				'code' => 'YQ',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Sports & Outdoors',
				'code' => 'YN',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'See all Children\'s eBooks',
				'code' => 'Y',
				'parent_id' => 61,
				'type' => 'international',
			],
			[
				'name' => 'Databases',
				'code' => 'UF; UM; UN',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'Graphic Design',
				'code' => 'AK; UG; UK; UM',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'Hardware',
				'code' => 'UK; UT',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'Microsoft',
				'code' => 'UM; UQ',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'Networking',
				'code' => 'UD; UT; TJ',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'Operating Systems',
				'code' => 'UL',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'Programming',
				'code' => 'UM; VS; PB',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'Software',
				'code' => 'UD; UF; UG; UM; UN; EL',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'Systems Analysis & Design',
				'code' => 'UY',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'Web Graphics',
				'code' => 'UG',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'Web Marketing',
				'code' => 'KJ',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'Web Site Design',
				'code' => 'UG',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'See all Computers & Technology',
				'code' => 'U',
				'parent_id' => 63,
				'type' => 'international',
			],
			[
				'name' => 'Baking',
				'code' => 'WBVS',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'Canning & Preserving',
				'code' => 'WBW',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'Cooking by Ingredient',
				'code' => 'WBT',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'Drinks & Beverages',
				'code' => 'WBX',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'Meals',
				'code' => 'WBV',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'Professional Cooking',
				'code' => 'WBB',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'Quick & Easy',
				'code' => 'WBF',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'Regional & International',
				'code' => 'WBN',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'Special Appliances',
				'code' => 'WBS',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'Special Diet',
				'code' => 'WBHS',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'Special Ocassions',
				'code' => 'WBR',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'Vegetables & Vegetarian',
				'code' => 'WBJ',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'See all cookbooks, food & wine',
				'code' => 'WB',
				'parent_id' => 64,
				'type' => 'international',
			],
			[
				'name' => 'Antiques & Colectibles',
				'code' => 'WC',
				'parent_id' => 65,
				'type' => 'international',
			],
			[
				'name' => 'Crafts & Hobbies',
				'code' => 'WF',
				'parent_id' => 65,
				'type' => 'international',
			],
			[
				'name' => 'Gardening & Horticulture',
				'code' => 'WM',
				'parent_id' => 65,
				'type' => 'international',
			],
			[
				'name' => 'Home Design',
				'code' => 'WK',
				'parent_id' => 65,
				'type' => 'international',
			],
			[
				'name' => 'How-to & Home Improvements',
				'code' => 'WK',
				'parent_id' => 65,
				'type' => 'international',
			],
			[
				'name' => 'Interior Design',
				'code' => 'AK; AM; WJ; WK',
				'parent_id' => 65,
				'type' => 'international',
			],
			[
				'name' => 'Weddings',
				'code' => 'VF; WJ',
				'parent_id' => 65,
				'type' => 'international',
			],
			[
				'name' => 'Childhood education',
				'code' => 'YB',
				'parent_id' => 66,
				'type' => 'international',
			],
			[
				'name' => 'Higher & continuing education',
				'code' => 'YQ; 4E; 4K',
				'parent_id' => 66,
				'type' => 'international',
			],
			[
				'name' => 'Studying & workbooks',
				'code' => 'EL',
				'parent_id' => 66,
				'type' => 'international',
			],
			[
				'name' => 'Teacher resources',
				'code' => '4E',
				'parent_id' => 66,
				'type' => 'international',
			],
			[
				'name' => 'Test preparation',
				'code' => '4E',
				'parent_id' => 66,
				'type' => 'international',
			],
			[
				'name' => 'See all education & teaching',
				'code' => '4',
				'parent_id' => 66,
				'type' => 'international',
			],
			[
				'name' => 'Automotive',
				'code' => 'KN; TR',
				'parent_id' => 67,
				'type' => 'international',
			],
			[
				'name' => 'Engineering',
				'code' => 'T',
				'parent_id' => 67,
				'type' => 'international',
			],
			[
				'name' => 'Transportation',
				'code' => 'WG; KN; TR',
				'parent_id' => 67,
				'type' => 'international',
			],
			[
				'name' => 'See all engineering & transportation',
				'code' => 'TR',
				'parent_id' => 67,
				'type' => 'international',
			],
			[
				'name' => 'Chinese',
				'code' => '2GDC',
				'parent_id' => 68,
				'type' => 'international',
			],
			[
				'name' => 'French',
				'code' => '2ADF',
				'parent_id' => 68,
				'type' => 'international',
			],
			[
				'name' => 'German',
				'code' => '2ACG',
				'parent_id' => 68,
				'type' => 'international',
			],
			[
				'name' => 'Italian',
				'code' => '2ADT',
				'parent_id' => 68,
				'type' => 'international',
			],
			[
				'name' => 'Japanese',
				'code' => '2GJ',
				'parent_id' => 68,
				'type' => 'international',
			],
			[
				'name' => 'Portuguese',
				'code' => '2ADP',
				'parent_id' => 68,
				'type' => 'international',
			],
			[
				'name' => 'Russian',
				'code' => '2AGR',
				'parent_id' => 68,
				'type' => 'international',
			],
			[
				'name' => 'Spanish',
				'code' => '2ADS',
				'parent_id' => 68,
				'type' => 'international',
			],
			[
				'name' => 'Other Languanges',
				'code' => '2Z',
				'parent_id' => 68,
				'type' => 'international',
			],
			[
				'name' => 'See all foreign languanges',
				'code' => '2',
				'parent_id' => 68,
				'type' => 'international',
			],
			[
				'name' => 'Addicition & recovery',
				'code' => 'YX; JF; MM',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Alternative medicine',
				'code' => 'MM; VXH',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Beauty, grooming & style',
				'code' => 'WJ',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Counselling & Psychology',
				'code' => 'VS; JM',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Death & grief',
				'code' => 'JH; VF; YX',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Diets & weight loss',
				'code' => 'VF; WB',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Diseases & physical ailments',
				'code' => 'MJ',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Exercise & fitness',
				'code' => 'VF; WS',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Nutrition',
				'code' => 'MB',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Personal health',
				'code' => 'MB; VF; VS',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Reference',
				'code' => 'VF; VS; VX',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Relationships',
				'code' => 'WJ; YX; JH; VF',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Safety & first aid',
				'code' => 'VF; JF',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Sex',
				'code' => 'VF; WJ; YX',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Sports Health & Safety',
				'code' => 'JM; MM',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Teen heath',
				'code' => 'YX',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'See all health, fitness & dieting',
				'code' => 'V',
				'parent_id' => 69,
				'type' => 'international',
			],
			[
				'name' => 'Africa',
				'code' => 'HBJH',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Americas',
				'code' => 'HBJK',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Ancient Civilizations',
				'code' => 'HBL',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Arctic & Antarctica',
				'code' => 'HBJQ',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Art & Literature',
				'code' => 'AC',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Asia',
				'code' => 'vHBJF',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Australia & Oceania',
				'code' => 'HBJM',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Europe',
				'code' => 'HBJD',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Food & Cooking',
				'code' => 'WB',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Hitorical Study',
				'code' => 'HB; YQH',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Middle East',
				'code' => 'HBJ',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Military',
				'code' => 'HBT',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Modern (16-21 Centuries)',
				'code' => 'HBL',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Religion',
				'code' => 'HR',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Rusia & Former Soviet Republics',
				'code' => 'HBT',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Science & Medicine',
				'code' => 'PD',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Social History',
				'code' => 'HBT',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'United States',
				'code' => 'HB',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'World',
				'code' => 'HBG',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'See all history',
				'code' => 'H',
				'parent_id' => 70,
				'type' => 'international',
			],
			[
				'name' => 'Humor',
				'code' => 'WH',
				'parent_id' => 71,
				'type' => 'international',
			],
			[
				'name' => 'Movies & Video',
				'code' => 'UD; AP',
				'parent_id' => 71,
				'type' => 'international',
			],
			[
				'name' => 'Performing Arts',
				'code' => 'AP',
				'parent_id' => 71,
				'type' => 'international',
			],
			[
				'name' => 'Pop Culture',
				'code' => 'JF',
				'parent_id' => 71,
				'type' => 'international',
			],
			[
				'name' => 'Puzzles & Games',
				'code' => 'UD; WD; WS',
				'parent_id' => 71,
				'type' => 'international',
			],
			[
				'name' => 'Radio',
				'code' => 'AP',
				'parent_id' => 71,
				'type' => 'international',
			],
			[
				'name' => 'Television',
				'code' => 'AP',
				'parent_id' => 71,
				'type' => 'international',
			],
			[
				'name' => 'See all Humor & Entertaiment',
				'code' => 'W',
				'parent_id' => 71,
				'type' => 'international',
			],
			[
				'name' => 'Administrative Law',
				'code' => 'LND',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Business',
				'code' => 'LNC',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Constitutional Law',
				'code' => 'LND',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Criminal Law',
				'code' => 'LB; LNF',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Environmental & Natural resources Law',
				'code' => 'LNK',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Ethics & Profesional Responsibility',
				'code' => 'LATC',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Family & health Law',
				'code' => 'LNM',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Intellectual Law',
				'code' => 'LNR',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Law Practice',
				'code' => 'LAS',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Legal Education',
				'code' => 'LR',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Media & The Law',
				'code' => 'LNJ',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Practical Guides',
				'code' => 'LA',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Procedures & Litigation',
				'code' => 'LA',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Specialities',
				'code' => 'LN',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Taxation',
				'code' => 'LNU',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'See all law',
				'code' => 'L',
				'parent_id' => 72,
				'type' => 'international',
			],
			[
				'name' => 'Action & Adventure',
				'code' => 'YFC; FJ',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Anthologies & Literature Collections',
				'code' => 'YD; DQ; YN',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Classics',
				'code' => 'FC; DB',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Contemporary Fiction',
				'code' => 'FA; YFT',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Drama & Plays',
				'code' => 'DD',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Erotica',
				'code' => 'FP',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Essays & Correspondence',
				'code' => 'DN',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Foreign Language Fiction',
				'code' => 'FYT',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Genre Fiction',
				'code' => 'FF; FH; FJ; FK; FL; FM; FP; FQ; FR; FT; FV; FW; FX',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Historical Fiction',
				'code' => 'FV',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'History & Critism',
				'code' => 'DS',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Horror',
				'code' => 'FK',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Humor & Satire',
				'code' => 'WH',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Literary Fiction',
				'code' => 'DD',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Mythology & Folk Tales',
				'code' => 'FQ',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Poetry',
				'code' => 'YD; DC',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Religious & Inpirational Fiction',
				'code' => 'FW',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Short Stories',
				'code' => 'YFU; FY',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'See all  Literature & Fiction',
				'code' => 'D, F',
				'parent_id' => 73,
				'type' => 'international',
			],
			[
				'name' => 'Administrative & Policy',
				'code' => 'MB',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Alternative & Holistic',
				'code' => 'VX',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Basic Science',
				'code' => 'MF',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Dentistry',
				'code' => 'MM; MMD',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Diseases',
				'code' => 'MJ',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Education & Training',
				'code' => 'MR',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Internal Medicine',
				'code' => 'MJ',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Nursing',
				'code' => 'MQ',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Pharmcology',
				'code' => 'MM; MMG',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Physician & Patient',
				'code' => 'MBD',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Reference',
				'code' => 'MR',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Reproductive Medicine & Technology',
				'code' => 'MFK',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Research',
				'code' => 'MM',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Special Topics',
				'code' => 'MX',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Veterinary Medicine',
				'code' => 'MZ',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'See all medical eBooks',
				'code' => 'M',
				'parent_id' => 74,
				'type' => 'international',
			],
			[
				'name' => 'Crime Fiction',
				'code' => 'FF',
				'parent_id' => 75,
				'type' => 'international',
			],
			[
				'name' => 'Mystery',
				'code' => 'FF',
				'parent_id' => 75,
				'type' => 'international',
			],
			[
				'name' => 'Suspense',
				'code' => 'FH',
				'parent_id' => 75,
				'type' => 'international',
			],
			[
				'name' => 'Thriller',
				'code' => 'FH',
				'parent_id' => 75,
				'type' => 'international',
			],
			[
				'name' => 'See all mystery, thriller & suspense',
				'code' => 'F',
				'parent_id' => 75,
				'type' => 'international',
			],
			[
				'name' => 'Arts & Photography',
				'code' => 'UD; AG; AJ; AK',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Biographies & Memoirs',
				'code' => 'BG; BM',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Bussiness & Investing',
				'code' => 'KJ',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Children\'s Non-fiction',
				'code' => 'YN',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Computers & Technology',
				'code' => 'TB; UB; UK; UM; UQ; UR; UY',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Cooking, Food & Wine',
				'code' => 'WB',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Craft, Hobbies & Home',
				'code' => 'WF',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Education & Reference',
				'code' => 'JN',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Engineering & Transportation',
				'code' => 'WG; TC; TG; TH; TJ; TN; TQ',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Health, Fitness & Dieting',
				'code' => 'VF; VX',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'History',
				'code' => 'HB',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Law',
				'code' => 'LA',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Literary Criticism & Theory',
				'code' => 'DS',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Medical ebooks',
				'code' => 'MB',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Parenting & Relationships',
				'code' => 'VF; JH',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Political & Social Sciences',
				'code' => 'JP',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Science',
				'code' => 'PD; PS',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Self-Help',
				'code' => 'VS',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Sports',
				'code' => 'WS',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Travel',
				'code' => 'WT',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'See all Non-fiction',
				'code' => 'D',
				'parent_id' => 76,
				'type' => 'international',
			],
			[
				'name' => 'Adoption',
				'code' => 'VF; JK',
				'parent_id' => 77,
				'type' => 'international',
			],
			[
				'name' => 'Aging Parents',
				'code' => 'VF; JK',
				'parent_id' => 77,
				'type' => 'international',
			],
			[
				'name' => 'Family Activities',
				'code' => 'VF',
				'parent_id' => 77,
				'type' => 'international',
			],
			[
				'name' => 'Family Health',
				'code' => 'VF',
				'parent_id' => 77,
				'type' => 'international',
			],
			[
				'name' => 'Family Relationships',
				'code' => 'VFV',
				'parent_id' => 77,
				'type' => 'international',
			],
			[
				'name' => 'Fertility',
				'code' => 'MF',
				'parent_id' => 77,
				'type' => 'international',
			],
			[
				'name' => 'Parenting',
				'code' => 'VFX',
				'parent_id' => 77,
				'type' => 'international',
			],
			[
				'name' => 'Special Needs',
				'code' => 'VFJB',
				'parent_id' => 77,
				'type' => 'international',
			],
			[
				'name' => 'See all Parenting & relationships',
				'code' => 'V',
				'parent_id' => 77,
				'type' => 'international',
			],
			[
				'name' => 'Crime & Criminals',
				'code' => 'BT; FF; JK; YF',
				'parent_id' => 78,
				'type' => 'international',
			],
			[
				'name' => 'Philosophy',
				'code' => 'HP',
				'parent_id' => 78,
				'type' => 'international',
			],
			[
				'name' => 'PolItics & Government',
				'code' => 'JP',
				'parent_id' => 78,
				'type' => 'international',
			],
			[
				'name' => 'Social Sciences',
				'code' => 'J',
				'parent_id' => 78,
				'type' => 'international',
			],
			[
				'name' => 'See all politics & social sciences',
				'code' => 'J',
				'parent_id' => 78,
				'type' => 'international',
			],
			[
				'name' => 'Almanacs & Yearbooks',
				'code' => 'GB',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Atlases & Maps',
				'code' => 'RG; WT; YR',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Catalogs & Directories',
				'code' => 'AG; GB',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Consumer Guides',
				'code' => 'WJ',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Dictionaries & Thesauruses',
				'code' => 'CB; EB; GB',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Encyclopedias',
				'code' => 'GB',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Etiquette',
				'code' => 'WJ',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Foreign Language Study & Reference',
				'code' => 'CB; YQ; YR',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Genealogy',
				'code' => 'GT; HB',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Medical Reference',
				'code' => 'MB; MF; MJ; MM; MQ; MR; PH; PS; TT',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Quotations',
				'code' => 'GB',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Trivia & Fun Facts',
				'code' => 'WD; YN',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Words, Language & Grammar',
				'code' => 'CB; CF; CJ; EL',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Writing, Research & Publishing Guides',
				'code' => 'YQ; GP; KJ; KN',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'See all reference',
				'code' => 'G',
				'parent_id' => 79,
				'type' => 'international',
			],
			[
				'name' => 'Agnoticism',
				'code' => 'HR',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Atheism',
				'code' => 'HRQ',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Buddhism',
				'code' => 'HRE',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Christian Books & Bibles',
				'code' => 'HRC',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Earth-Based Religions',
				'code' => 'HRQ',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Hinduism',
				'code' => 'HRG',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Islam',
				'code' => 'HRH',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Judaism',
				'code' => 'HRJ',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'New Age',
				'code' => 'AV',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Occult',
				'code' => 'HRQ',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Other Eastern Religions & Sacred Texts',
				'code' => 'HRK',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Other Religions, Practices & Sacred Texts',
				'code' => 'HRL',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Religious Fiction',
				'code' => 'FW',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Religious Studies & Reference',
				'code' => 'JF; JP; YN; YQ',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Spirituality',
				'code' => 'HR',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'See all religion & spirituality',
				'code' => 'H',
				'parent_id' => 80,
				'type' => 'international',
			],
			[
				'name' => 'Contemporary',
				'code' => 'FA',
				'parent_id' => 81,
				'type' => 'international',
			],
			[
				'name' => 'Fantasy',
				'code' => 'FM; YF',
				'parent_id' => 81,
				'type' => 'international',
			],
			[
				'name' => 'Historical Romance',
				'code' => 'FR',
				'parent_id' => 81,
				'type' => 'international',
			],
			[
				'name' => 'Mystery & Suspense',
				'code' => 'FR',
				'parent_id' => 81,
				'type' => 'international',
			],
			[
				'name' => 'Science Fiction',
				'code' => 'FX',
				'parent_id' => 81,
				'type' => 'international',
			],
			[
				'name' => 'See all romance',
				'code' => 'FR',
				'parent_id' => 81,
				'type' => 'international',
			],
			[
				'name' => 'Agricultural Sciences',
				'code' => 'PG; TT; WN',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Astronomy & Space Science',
				'code' => 'JM; PS',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Behavioural Sciences',
				'code' => 'PS; RN; WN',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Biological Sciences',
				'code' => 'PN;  PS; RB; TD',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Chemistry',
				'code' => 'RB; WN',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Earth Sciences',
				'code' => 'VS; WS; YQ; YX; 4',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Education',
				'code' => 'HD; RN; TQ; WN',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Enviroment',
				'code' => 'DN',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Essays & Commentary',
				'code' => 'PS',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Evolution',
				'code' => 'PD',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Experiments, Instruments & Measurement',
				'code' => 'PS; MF',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Genetics',
				'code' => 'WQ; CF; HB; HP',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'History & Philosophy',
				'code' => 'PB',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Mathematics',
				'code' => 'M',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Medicine',
				'code' => 'PS; RN',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Nature & Ecology',
				'code' => 'PH',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Physics',
				'code' => 'GB; GL; MR',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Reference',
				'code' => 'T; UB; UT; YQ; 4K',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'See all science & Math',
				'code' => 'P',
				'parent_id' => 82,
				'type' => 'international',
			],
			[
				'name' => 'Fantasy',
				'code' => 'FM',
				'parent_id' => 83,
				'type' => 'international',
			],
			[
				'name' => 'Science Fiction',
				'code' => 'FL',
				'parent_id' => 83,
				'type' => 'international',
			],
			[
				'name' => 'See all science fiction & fantasy',
				'code' => 'F',
				'parent_id' => 83,
				'type' => 'international',
			],
			[
				'name' => 'Creativity',
				'code' => 'CBV',
				'parent_id' => 84,
				'type' => 'international',
			],
			[
				'name' => 'Eating Disorders & Body Image',
				'code' => 'VFJJ',
				'parent_id' => 84,
				'type' => 'international',
			],
			[
				'name' => 'Happiness',
				'code' => 'VSP',
				'parent_id' => 84,
				'type' => 'international',
			],
			[
				'name' => 'Inner Child',
				'code' => 'VSP',
				'parent_id' => 84,
				'type' => 'international',
			],
			[
				'name' => 'Journal Writing',
				'code' => 'CBW; CBV',
				'parent_id' => 84,
				'type' => 'international',
			],
			[
				'name' => 'Memory Improvement',
				'code' => 'VSPT',
				'parent_id' => 84,
				'type' => 'international',
			],
			[
				'name' => 'Motivational',
				'code' => 'VSPM',
				'parent_id' => 84,
				'type' => 'international',
			],
			[
				'name' => 'Personal Transformation',
				'code' => 'VS',
				'parent_id' => 84,
				'type' => 'international',
			],
			[
				'name' => 'Self-Esteem',
				'code' => 'VSPM',
				'parent_id' => 84,
				'type' => 'international',
			],
			[
				'name' => 'Spiritual',
				'code' => 'HRCS; HRLK; HRQM2',
				'parent_id' => 84,
				'type' => 'international',
			],
			[
				'name' => 'Stress Management',
				'code' => 'VFJS',
				'parent_id' => 84,
				'type' => 'international',
			],
			[
				'name' => 'See all self-help',
				'code' => 'V',
				'parent_id' => 84,
				'type' => 'international',
			],
			[
				'name' => 'Baseball',
				'code' => 'WSJT',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Basketball',
				'code' => 'WSJM',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Biographies',
				'code' => 'BGS',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Coaching',
				'code' => 'WSD',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Extreme Sports',
				'code' => 'WSE',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Football (American)',
				'code' => 'WSJF',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Golf',
				'code' => 'WSJG',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Hockey',
				'code' => 'WSJH',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Mountaineering',
				'code' => 'WSZG',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Outdoors & Nature',
				'code' => 'WSZ',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Poker',
				'code' => 'WDMC2',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Racket Sports',
				'code' => 'WSJR',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Rodeos',
				'code' => 'WSN',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Soccer',
				'code' => 'WSJA',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Softball',
				'code' => 'WSJT',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Training',
				'code' => 'WSL',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Water Sports',
				'code' => 'WSS',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Winter Sports',
				'code' => 'WSW',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'See all sports & outdoors',
				'code' => 'WS',
				'parent_id' => 85,
				'type' => 'international',
			],
			[
				'name' => 'Art, Music & Photography',
				'code' => 'YN',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Biography',
				'code' => 'BGF',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Comics & Graphic Novels',
				'code' => 'YFW',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Education & Reference',
				'code' => 'YQ',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Historial Fiction',
				'code' => 'YFT',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Horror',
				'code' => 'YFD',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Literature & Fiction',
				'code' => 'YFA; YNL',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Mysteries & Thrillers',
				'code' => 'YFC',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Personal health',
				'code' => 'YX',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Religion & Spirituality',
				'code' => 'YXZR; YQR',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Romance',
				'code' => 'YFM',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Science Fiction & Fantasy',
				'code' => 'YFG; YFH',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Social Issues',
				'code' => 'YXZ',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Sports & Outdoors',
				'code' => 'YNW',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'See all teen & young adult',
				'code' => 'Y',
				'parent_id' => 86,
				'type' => 'international',
			],
			[
				'name' => 'Africa',
				'code' => 'WTR; 1H',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'Asia',
				'code' => 'WTR; 1F',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'Australia & South Pacific',
				'code' => 'WTR; 1M',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'Canada',
				'code' => 'WTR; 1KBC',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'Caribbean',
				'code' => 'WTR; 1KJ',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'Central & South Asia',
				'code' => 'WTR; 1FC; 1FM',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'Europe',
				'code' => 'WTR; 1D',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'Food, Lodging & Transportation',
				'code' => 'WTH',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'Middle East',
				'code' => 'WTR; 1FB',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'Pictorial',
				'code' => 'WTM',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'Polar Regions',
				'code' => 'WTR; 1MT',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'Reference',
				'code' => 'WZ; GBG',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'Travel Writing',
				'code' => 'WTL',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'United States',
				'code' => 'WTR; 1K',
				'parent_id' => 87,
				'type' => 'international',
			],
			[
				'name' => 'See all travel',
				'code' => 'WT',
				'parent_id' => 87,
				'type' => 'international',
			],
		]);
	}
}
